# Generated by Django 4.0.6 on 2023-04-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_biodata_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='biodata',
            name='username',
            field=models.CharField(default=2, max_length=256),
            preserve_default=False,
        ),
    ]
