# Generated by Django 4.0.6 on 2023-02-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biodata',
            name='email',
            field=models.EmailField(default=123, max_length=254),
            preserve_default=False,
        ),
    ]
