# Generated by Django 4.0.6 on 2023-04-09 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_biodata_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='biodata',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='biodata',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='biodata',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='biodata',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
